name: kotaklog-api

services:
  postgres:
    image: postgres
    container_name: kotaklog-api-postgres
    environment:
      POSTGRES_DB: kotaklog-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - kotaklog-api_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  kotaklog-api_postgres_data: